#!/bin/bash

# Copyright (C) 2013-2015 The SaberMod Project

#Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Initially define script naming form
export FORM=$ARCH/$ARCH$TARGET-$VER
export TRUE=y

# Ask for GCC Version to build
echo "Which GCC version would you like to build?"

while read -p "4.8, 4.9, 5.0, or all?" cchoice
do
case "$cchoice" in
	4.8 )
		export VER=4.8
		break
		;;
	4.9 )
		export VER=5.0
		break
		;;
	5.0 )
		export VER=5.0
		break
		;;
	all )
		export VER=all
		export FORM=$VER-$ARCH
		break
		;;
esac
done

# Ask what arch to build for
echo 
echo "Which arch would you like to build for?"

while read -p "arm, aarch64, or x86_64? " cchoice
do
case "$cchoice" in
	arm )
		export ARCH=arm
		export USE_TARGET=y
		break
		;;
	aarch64 )
		export VER=aarch64
		export USE_TARGET=n
		export TARGET=-linux
		break
		;;
	x86_64 )
		export VER=x86_64
		export USE_TARGET=n
		export TARGET=-linux
		break
		;;
esac
done

# Only ask for target if ARM is selected
if [[ $USE_TARGET -eq $TRUE ]]; then
  echo 
  echo "Would you like to build a ROM toolchain or Kernel toolchain?"

  while read -p "ROM or Kernel? " cchoice
  do
  case "$cchoice" in
	ROM )
		export TARGET=-linux-androideabi
		break
		;;
	kernel )
		export TARGET=-eabi
		break
		;;
  esac
  done
fi

# Build Toolchain
bash $FORM
