#!/bin/bash

# Copyright (C) 2015 The SaberMod Project

#Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Export any command-line options

if test -d smbuild;
then
    export CORTEX=$1;
    export NEON=$2;

    ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";

    # Ask for GCC Version to build
    echo "Which GCC version would you like to build?";

    while read -p "4.8, 4.9, 5.1, 5.2 or 6.0? " cchoice
    do
    case "$cchoice" in
    4.8 )
        export VER=4.8;
        break;
        ;;
    4.9 )
        export VER=4.9;
        break;
        ;;
    5.1 )
        export VER=5.1;
        break;
        ;;
    5.2 )
        export VER=5.2;
        break;
        ;;
    6.0 )
        export VER=6.0;
        break;
        ;;
    esac
    done

    # Ask what arch to build for
    echo;
    echo "Which arch would you like to build for?";

    while read -p "arm, aarch64, or x86_64? " cchoice
    do
    case "$cchoice" in
    arm )
        export ARCH=arm;
        break;
        ;;
    aarch64 )
        export ARCH=aarch64;
        break;
        ;;
    x86_64 )
        export ARCH=x86_64;
        export TARGET=-linux;
        break;
        ;;
    esac
    done

    # Ask for ROM or Kernel toolchains for arm and aarch64
    if [ $ARCH != x86_64 ];
    then
        echo; 
        echo "Would you like to build a ROM toolchain or Kernel toolchain?";

        while read -p "rom or kernel? " cchoice
        do
        case "$cchoice" in
	rom )

            if [ $ARCH = "arm" ];
            then
                export TARGET=-linux-androideabi;
            fi;
            if [ $ARCH = "aarch64" ];
            then
                export TARGET=-linux-android;
            fi;
            break
            ;;
	kernel )

            if [ $ARCH = "arm" ];
            then
                export TARGET=-eabi;
            fi;
            break
            ;;

      esac
      done
    fi;
else
    echo "";
    echo "";
    echo "";
    echo "Please run this script from the root of the toolchain source instead of smbuild.";
    echo "";
    echo "";
    echo "";
    exit 1;
fi;
# Build Toolchain
cd smbuild/$ARCH;
bash $ARCH$TARGET-$VER;
cd $ROOT_DIR;
