#!/bin/bash

# Copyright (C) 2014-2015 The SaberMod Project
# This file is free software; The SaberMod Project
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

SHORT_LOG=`grep -r "error:" $MAKE_LOG > $LOG_PATH/$SET_TARGET-$SET_TARGET_GCC_MAJOR-$SET_TARGET_GCC_MINOR-SHORT.log`;

panic ()
{
    echo -e "${CLR_BLD_RED}ERROR:${CLR_RST} ${CLR_RED}$@${CLR_RST}";
}

if [ $CLOOG_INSTALLED = "no" ];
then
    $SHORT_LOG;
    echo "";
    echo "";
    echo "";
panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************

       Sorry your build failed because
       host CLOOG libraries failed to install

       Email log to:
           sabermod.team@gmail.com
           for assistance.

       Full Log is located at:
           $MAKE_LOG

       Short Log is located at:
           $LOG_PATH/$SET_TARGET-$SET_TARGET_GCC_MAJOR-$SET_TARGET_GCC_MINOR-SHORT.log

        **************************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
    echo "";
    echo "";
    echo "";

elif [ $ISL_INSTALLED = "no" ];
then
    $SHORT_LOG;
    echo "";
    echo "";
    echo "";
panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************

       Sorry your build failed because
       host ISL libraries failed to install

       Email log to:
           sabermod.team@gmail.com
           for assistance.

       Full Log is located at:
           $MAKE_LOG

       Short Log is located at:
           $LOG_PATH/$SET_TARGET-$SET_TARGET_GCC_MAJOR-$SET_TARGET_GCC_MINOR-SHORT.log

        **************************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
    echo "";
    echo "";
    echo "";

elif [ $MPC_INSTALLED = "no" ];
then
    $SHORT_LOG;
    echo "";
    echo "";
    echo "";
panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************

       Sorry your build failed because
       host MPC libraries failed to install

       Email log to:
         sabermod.team@gmail.com
         for assistance.

       Full Log is located at:
           $MAKE_LOG

       Short Log is located at:
           $LOG_PATH/$SET_TARGET-$SET_TARGET_GCC_MAJOR-$SET_TARGET_GCC_MINOR-SHORT.log

        **************************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
    echo "";
    echo "";
    echo "";

elif [ $MPFR_INSTALLED = "no" ];
then
    $SHORT_LOG;
    echo "";
    echo "";
    echo "";
panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************

       Sorry your build failed because
       host MPFR libraries failed to install

       Email log to:
         sabermod.team@gmail.com
         for assistance.

       Full Log is located at:
           $MAKE_LOG

       Short Log is located at:
           $LOG_PATH/$SET_TARGET-$SET_TARGET_GCC_MAJOR-$SET_TARGET_GCC_MINOR-SHORT.log

        **************************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
    echo "";
    echo "";
    echo "";

elif [ $GMP_INSTALLED = "no" ];
then
    $SHORT_LOG;
    echo "";
    echo "";
    echo "";
panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************

       Sorry your build failed because
       host GMP libraries failed to install

       Email log to:
         sabermod.team@gmail.com
         for assistance.

       Full Log is located at:
           $MAKE_LOG

       Short Log is located at:
           $LOG_PATH/$SET_TARGET-$SET_TARGET_GCC_MAJOR-$SET_TARGET_GCC_MINOR-SHORT.log

        **************************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
    echo "";
    echo "";
    echo "";
else
    if [ $SET_TARGET_BUILD = "GCC" ];
    then
        $SHORT_LOG;
        echo "";
        echo "";
        echo "";
panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************

       GCC has failed to build
       Read:
         https://gitlab.com/SaberMod/sabermod-manifest/blob/master/README.md
         for system requirements and instructions.

       Email log to:
         sabermod.team@gmail.com
         for assistance.

       Full Log is located at:
           $MAKE_LOG

       Short Log is located at:
           $LOG_PATH/$SET_TARGET-$SET_TARGET_GCC_MAJOR-$SET_TARGET_GCC_MINOR-SHORT.log

        **************************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
        echo "";
        echo "";
        echo "";
    fi;
fi;

unset CLOOG_INSTALLED;
unset ISL_INSTALLED;
unset MPFR_INSTALLED;
unset GMP_INSTALLED;
unset SET_TARGET_BUILD;
